### ISSUE TITLE
Create new project roster form

### ISSUE THREAD

**Issue by dazzaji** [OpenInnovationNetwork/2016-MIT-IAP-PrototypeJam#1]
Use the futurecommerce form as initial draft.  Modify:
Add pull down menu for the participant
Add link to project page and URL at mit.edu/law/blockchain/projects/

Send email to all with project inviting them to participate and to fill out the form so we have permission to create a public project page for them and match them with mentors.

**Comment by creckhow-zz** [comment]
https://docs.google.com/a/consensys.net/forms/d/1WSNlwFoqHFoBsHCpgr-s5sLH8wBWZXXmYw-BuL1nX1k/edit?ts=568af6e8 

Here's the form

**Comment by dazzaji** [comment]
Let us send an email welcome to everyone and a special email to people with projects (with link to this form) tonight.

**Comment by creckhow-zz** [comment]
Great! Do it.
ᐧ

On Mon, Jan 4, 2016 at 5:51 PM, Dazza Greenwood notifications@github.com
wrote:

> Let us send an email welcome to everyone and a special email to people
> with projects (with link to this form) tonight.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenInnovationNetwork/2016-MIT-IAP-PrototypeJam/issues/1#issuecomment-168836989
> .

## 

_Carolyn Reckhow_ // _Communications_
carolyn.reckhow@consensys.net  carolyn.reckhow@consensys.net//
413.230.4801
49 Bogart St. Brooklyn, NY 11237

**Comment by creckhow-zz** [comment]
New Form Here: 

https://docs.google.com/forms/d/1WSNlwFoqHFoBsHCpgr-s5sLH8wBWZXXmYw-BuL1nX1k/viewform?c=0&w=1

**Comment by dazzaji** [comment]
This is done now and is working very nicely.  Thank you.
