### ISSUE TITLE
Add "IDE provided by <ether.camp>" on mit.edu/law/blockchain

### ISSUE THREAD

**Issue by creckhow-zz** [OpenInnovationNetwork/2016-MIT-IAP-PrototypeJam#10]

**Comment by dazzaji** [comment]
We need to find out whether this guy is coming and if so, when and for how long and what reasonable level of support/contribution can be expected in advance, at the time and after (if any).  In that context, we can create some attribution for contribution.  We need to firm up the schedule and definition of how the IDE will be supported and add attribution to the company providing this after that is done.

**Comment by creckhow-zz** [comment]
I'm 80% sure Roman will be flying into Boston. We can expect support
before, during and after Tuesday.
ᐧ

On Sat, Jan 9, 2016 at 6:37 AM, Dazza Greenwood notifications@github.com
wrote:

> Reopened #10
> https://github.com/OpenInnovationNetwork/2016-MIT-IAP-PrototypeJam/issues/10
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenInnovationNetwork/2016-MIT-IAP-PrototypeJam/issues/10#event-510176218
> .

## 

_Carolyn Reckhow_ // _Communications_
carolyn.reckhow@consensys.net  carolyn.reckhow@consensys.net//
413.230.4801
49 Bogart St. Brooklyn, NY 11237
