### ISSUE TITLE
Collaborators Page on law/blockchain

### ISSUE THREAD

**Issue by creckhow-zz** [OpenInnovationNetwork/2016-MIT-IAP-PrototypeJam#13]
https://docs.google.com/document/d/1tojzyTkZN77kMlcFHCRwZycKU5GDn6Gx67s0NDN1Q5c/edit#

**Comment by dazzaji** [comment]
DONE!

---

   |   Daniel "Dazza" Greenwood http://dazzagreenwood.com/
   |   CIVICS.com http://civics.com/ & Law.MIT.edu http://law.mit.edu/
   |   dazza@CIVICS.com & 617.500.3644
   |   1 Broadway, 14th Floor, Cambridge, MA 02142
