### ISSUE TITLE
Add section on mit.edu/law/blockchain for ConsenSys Resources deck

### ISSUE THREAD

**Issue by creckhow-zz** [OpenInnovationNetwork/2016-MIT-IAP-PrototypeJam#3]
https://docs.google.com/presentation/d/1Ph4gAlaho47DsXZQfPLTe4o067hpQAfCX4WKZtN7mGM/edit#slide=id.gec910f06e_0_68

**Comment by dazzaji** [comment]
Is this done?  It sounds like the deck that is already in the site, right?

**Comment by creckhow-zz** [comment]
No, this is a different deck, not up on the site yet. It's got all the
videos and resources from ConsenSys speakers. This one:

https://docs.google.com/presentation/u/1/d/1Ph4gAlaho47DsXZQfPLTe4o067hpQAfCX4WKZtN7mGM/edit#slide=id.p

ᐧ

On Sat, Jan 9, 2016 at 6:43 AM, Dazza Greenwood notifications@github.com
wrote:

> Is this done? It sounds like the deck that is already in the site, right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenInnovationNetwork/2016-MIT-IAP-PrototypeJam/issues/3#issuecomment-170228714
> .

## 

_Carolyn Reckhow_ // _Communications_
carolyn.reckhow@consensys.net  carolyn.reckhow@consensys.net//
413.230.4801
49 Bogart St. Brooklyn, NY 11237
