### ISSUE TITLE
Communication Channels - Invite Participants 

### ISSUE THREAD

**Issue by creckhow-zz** [OpenInnovationNetwork/2016-MIT-IAP-PrototypeJam#4]
Slack 

Gitter 

Emails here https://docs.google.com/spreadsheets/d/1ZaUUAHndJFFdPHSC8mkZiDrSDnY6VsURGzu4u5WP54Y/edit#gid=0

**Comment by dazzaji** [comment]
Let's try to incorporate the following hack (I can ask Jason Walsh for a hand tomorrow if needed):

https://github.com/outsideris/slack-invite-automation

**Comment by creckhow** [comment]
Add Mohammed -- new participant just registered Monday night.

**Comment by dazzaji** [comment]
To embed Slack into the live session page, let's try this:
http://www.programmableweb.com/news/embed-real-time-chat-functionality-slacks-messaging-api/brief/2015/01/19 

also see the code here: http://www.programmableweb.com/api/slack-real-time-messaging

**Comment by dazzaji** [comment]
To this Slack channel: 
https://opencollab.slack.com/messages/blockchain-projects/

**Comment by creckhow-zz** [comment]
Dazza - if you change my status to "administrator" (see here https://get.slack.help/hc/en-us/articles/201314026-Roles-and-permissions-in-Slack) I can do this.

**Comment by dazzaji** [comment]
Your status was changed that day.  Is this all set?

**Comment by creckhow-zz** [comment]
All set!
ᐧ

On Sat, Jan 9, 2016 at 6:43 AM, Dazza Greenwood notifications@github.com
wrote:

> Your status was changed that day. Is this all set?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenInnovationNetwork/2016-MIT-IAP-PrototypeJam/issues/4#issuecomment-170228742
> .

## 

_Carolyn Reckhow_ // _Communications_
carolyn.reckhow@consensys.net  carolyn.reckhow@consensys.net//
413.230.4801
49 Bogart St. Brooklyn, NY 11237
