### ISSUE TITLE
Issue with joining Slack channel

### ISSUE THREAD

**Issue by BabakKia** [OpenInnovationNetwork/2016-MIT-IAP-PrototypeJam#7]
Good people of 2016-MIT-IAP:

Maybe it's just me, but it appears that I can't login to the slack link sent.  For some reason it (the link) believes that I already have a password.  

For faster communiques, feel free to chat on Google Hangouts.

Thank you!
Babak

**Comment by dazzaji** [comment]
sorry about the hiccup with slack signup.  we'll take a look and try to help you get this sorted out today.
thanks,
